version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: url
     POSTGRES_DB: project
     POSTGRES_PASSWORD: url.2024

